RootApp/CRUD/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('index/', views.index, name = 'index-book'),
    path('', views.home, name = 'home'),
    path('edit/<int:id>', views.edit, name = 'edit'),
    path('update/<int:id>', views.update, name = 'update'),
    path('remove/<int:id>', views.remove, name = 'remove'),








]

RootApp/RootApp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CRUD.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

RootApp/CRUD/models.py
from django.db import models
# from django.urls import reverse

# Create your models here.
class BookList(models.Model):
    title = models.CharField(max_length=30)
    price = models.IntegerField()
    author = models.CharField(max_length=20)

    def __str__(self):
        return self.title
    # def get_absolute_url(self):
    #     return reverse('book_edit', kwargs={'pk':self.pk})

RootApp/CRUD/forms.py
from django import  forms
from CRUD.models import BookList


class BookForm(forms.ModelForm):
    class Meta:
        model = BookList
        fields  = "__all__"

RootApp/CRUD/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from CRUD.models import BookList
from CRUD.forms import BookForm

# Create your views here.

def index(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():

            form.save()
            return redirect('/')

    else:
        form = BookForm()
    return render(request, 'CRUD/index.html', {'form': form})

def home(request):
    books = BookList.objects.all()
    return render(request, 'CRUD/home.html',{'books':books})

def edit(request,id):
    book = BookList.objects.get(pk=id)
    return render(request,'CRUD/edit.html', {'book':book})

def update(request,id):
    book = BookList.objects.get(pk=id)
    form = BookForm(request.POST,instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'CRUD/edit.html',{'book':book})
def remove(request,id):
    book = BookList.objects.get(pk=id)
    book.delete()

    return redirect('/')

RootApp/templates/CRUD/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CRUD</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}

</div>






<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

RootApp/templates/CRUD/edit.html
{% extends 'CRUD/base.html' %}
{% block content %}

<form method="POST" class="post-form" action="/update/{{book.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Title:</label>
    <div class="col-sm-4">
        <input type="text" name="title" id="id_title" required maxlength="20" value="{{ book.title }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Price:</label>
    <div class="col-sm-4">
        <input type="text" name="price" id="id_price" required maxlength="100" value="{{ book.price }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Author:</label>
    <div class="col-sm-4">
        <input type="text" name="author" id="id_author" required maxlength="254" value="{{ book.author }}" />
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
{% endblock %}

RootApp/templates/CRUD/home.html
{% extends 'CRUD/base.html' %}
{% block content %}
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Author</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for book in books %}
    <tr>
        <td>{{ book.title }}</td>
        <td>{{ book.price}}</td>
        <td>{{ book.author }}</td>

        <td>
            <a href="/edit/{{ book.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/remove/{{ book.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/index" class="btn btn-primary">Add New Record</a></center>


{% endblock %}

RootApp/templates/CRUD/index.html
{% extends 'CRUD/base.html' %}


{% block content %}
    <div class="container">
        <h2>Book List</h2>
        <hr>

<form method="POST" class="post-form" action="/index">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Title:</label>
    <div class="col-sm-4">
      {{ form.title }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Price:</label>
    <div class="col-sm-4">
      {{ form.price }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Author:</label>
    <div class="col-sm-4">
      {{ form.author }}
    </div>
  </div>

    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
{% endblock %}